---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/estela5839/public_html
    - /bin/cp -R imagenes $DEPLOYPATH
    - /bin/cp -R CANDARA $DEPLOYPATH
    - /bin/cp -R Tipografías $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R comportamiendoIndex.js $DEPLOYPATH
    - /bin/cp -R ingles.html $DEPLOYPATH
    - /bin/cp -R estilosGeneral.css $DEPLOYPATH
